### ISSUE TITLE
Apply colour scheme, typography, UI elements interaction based on #295

### ISSUE THREAD

**Issue by mmmavis** [mozilla/lightbeam#330]
Apply colour scheme, typography, UI elements interaction based on #295 
- [x] Colour Scheme
- [x] Typography

Related Issues:
- [x] #272 Menu Control Panel Design
- [x] #301 Legend and Control Button Design (for Graph + Clock view)
- [x] #302 Site Preference Buttons (for list view)
