### ISSUE TITLE
Replace placeholder text

### ISSUE THREAD

**Issue by mmmavis** [mozilla/lightbeam#389]
- [x] Pop-up dialogs (#372, #380, etc)  
- [x] Privacy Policy text on the About section(Info Panel) 
- [x] Help & About sections on Add-on (#317)
- [x] links mentioned on Add-on (#390)
- [x] Legend
