### ISSUE TITLE
Checklist for MozFest

### ISSUE THREAD

**Issue by dethe** [mozilla/lightbeam#447]
# For JP
- [x] Environment variables on staging
- [ ] Deploy to production
# Add-on
- [x] Search and replace on name
- [x] Add icon
- [x] Copy edit
- [ ] Check on issue #446 
- [x] Issue #365 (fixed)  
- [x] Issue #197 
- [x] Issue #372
- [x] Point add-on at production database server
- [x] Change app ID
- [x] Submit for review
# Database
- [x] Remove caching for now on staging
- [x] Research and fix caching on staging
- [x] Test production
- [ ] Spider to populate
# Website
- [x] Install bedrock locally
- [x] Search and replace name
- [x] Add icon
- [x] Copy edit
- [x] Add images
- [x] Submit for review
# AMO Site
- [x] Update text, icon, screenshots
# MozFest (not neccesarily collusion-related, but impacts timeline)
- [x] Comms report
- [x] Reply to presenter questions
- [ ] Schedule meeting with jbuck & rory
- [x] Meet with Michelle
